services:
  flowchart_vqa:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    runtime: nvidia
    environment:
      - CUDA_VISIBLE_DEVICES=all

  flowchart_vqa_cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./logs:/app/logs
      - ./output:/app/output
    environment:
      # disable flash-attention at runtime for CPU container
      - ENABLE_FLASH_ATTENTION=0